name: imo
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_route: ^3.2.4
  go_router: ^3.0.7
  flutter_bloc: ^8.0.1
  rxdart: ^0.27.3
  equatable: ^2.0.3
  dio: ^4.0.6
  logger: ^1.1.0
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  # uı widgets
  reorderable_grid: ^1.0.3

  # util
  flutter_screenutil: ^5.4.0
  flutter_svg: ^1.0.3
  google_fonts: ^2.3.1
  clipboard: ^0.1.3
  image: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  build_runner: ^2.1.8
  auto_route_generator: ^3.2.3
  hive_generator: ^1.1.2

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/image/
    - assets/svg/
